### PR TITLE
Fix panic for corrupt replays

### LINKED ISSUE #19: Parsing replay files can panic in debug mode.
[Line 829 in serde/de.rs](https://github.com/hohav/peppi/blob/9477e8c22fe7a93928449d87ce9c436618f56f49/peppi/src/serde/de.rs#L829) can overflow and panic if the replay file is corrupted. The function should return a ParseError instead. I have had this happen on actual replay files that were generated by Slippi, so it doesn't even require random garbage to trigger (I'm not sure why they are corrupted, but I have dozens of such files from playing thousands of games).

There may be other possible places that could panic, but I have not checked the entire parsing code. Any unchecked arithmetic is a potential overflow though. On these particular files it only panics if I am skipping frames though.

Example file attached. Note however that I'm not asking why the file doesn't parse, I know it's corrupt. I'm just saying that the parsing functions should not panic.

[corrupt.zip](https://github.com/hohav/peppi/files/9386783/corrupt.zip)

### PR DESCRIPTION
**Pull request by NickCondron**
Fixes #19

### CODE REVIEW

File: peppi/src/serde/de.rs [hunk 1]
```diff
@@ -972,7 +972,13 @@ pub fn deserialize<R: Read, H: Handlers>(
 	while (raw_len == 0 || bytes_read < raw_len) && last_event != Some(Event::GameEnd) {
 		if skip_frames && last_event == Some(Event::GameStart) {
 			// Skip to GameEnd, which we assume is the last event in the stream!
-			let skip = raw_len - bytes_read - payload_sizes[&(Event::GameEnd as u8)] as usize - 1;
+			let end_offset: usize = payload_sizes[&(Event::GameEnd as u8)] as usize + 1;
+			if raw_len == 0 || raw_len - bytes_read < end_offset {
```
Comment (hohav) [inline peppi/src/serde/de.rs:976]: I think this can just be `if skip < 0` if you move it below `let skip = ...`.

File: peppi/tests/peppi.rs [hunk 2]
```diff
@@ -581,6 +581,12 @@ fn unknown_event() -> Result<(), Error> {
 	Ok(())
 }
 
+#[test]
+fn corrupt_replay() -> Result<(), Error> {
+	assert!(matches!(game("corrupt"), Err(_)));
```
Comment (hohav) [inline peppi/tests/peppi.rs:586]: You'll also need to add this replay to the exclusions in `round_trip()`, since that now iterates over all test replays by default.

File: peppi/src/serde/de.rs (hunk 1 above)
Comment (NickCondron) [reply peppi/src/serde/de.rs:976]: The panic actually happens on the subtraction because the corrupt replay has `raw_len` as 0.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8e5f0273ee8001e570ea133c02e3446f

The alternative is to do a bunch of ugly casts to/from `usize`, but I don't think that would make sense here.

**Comment by NickCondron** [comment]
* Rebased
* Added corrupt replay to exclusions for `round_trip`
* Slightly modified `tests/common/mod.rs` to make testing for errors easier
